[workspace]
authors = ["SoundDrill31 <84176052+sounddrill31@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "website"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "python build.py"
dev = "python build.py && python -m http.server --directory out"

[dependencies]
python = ">=3.13.7,<3.14"
pyyaml = ">=6.0.3,<7"
jinja2 = ">=3.1.6,<4"
